# Automatically generated by configure
PREFIX=/64/L/
bindir=/64/L//bin
libdir=/64/L//lib
incdir=/64/L//include/sys
AR=/usr/bin/x86_64-w64-mingw32-ar
CC=/usr/bin/x86_64-w64-mingw32-gcc
RANLIB=/usr/bin/x86_64-w64-mingw32-ranlib
STRIP=/usr/bin/x86_64-w64-mingw32-strip
BUILD_STATIC=yes
BUILD_SHARED=yes
BUILD_MSVC=
LIBCMD=echo ignoring lib
