# Automatically generated by configure
PREFIX=/32/L/
bindir=/32/L//bin
libdir=/32/L//lib
incdir=/32/L//include/sys
AR=/usr/bin/i686-w64-mingw32-ar
CC=/usr/bin/i686-w64-mingw32-gcc
RANLIB=/usr/bin/i686-w64-mingw32-ranlib
STRIP=/usr/bin/i686-w64-mingw32-strip
BUILD_STATIC=yes
BUILD_SHARED=yes
BUILD_MSVC=
LIBCMD=echo ignoring lib
